# Generated by Django 4.2.7 on 2024-01-12 06:50

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='india@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='reneteremail',
            field=models.EmailField(default='india@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='smobile',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('[6-9]\\d{9}')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='sname',
            field=models.CharField(max_length=100, validators=[app.models.validate_for_a]),
        ),
    ]
